# Generated by Django 5.2.3 on 2025-06-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansisAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], default='I', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, max_digits=64)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finansisAPI.category')),
            ],
        ),
    ]
