# Generated by Django 5.2.3 on 2025-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansisAPI', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
