# Generated by Django 5.2.3 on 2025-06-16 16:07

import finansisAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansisAPI', '0003_remove_entry_name_alter_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(finansisAPI.models.get_other_category), to='finansisAPI.category'),
        ),
    ]
