# Generated by Django 5.2.1 on 2025-05-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('number', models.CharField(db_column='number', max_length=10)),
                ('company', models.CharField(db_column='company', max_length=30)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('cpf', models.CharField(db_column='cpf', max_length=11)),
                ('balance', models.BigIntegerField(db_column='balance', default=0)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('card_number', models.CharField(db_column='card_number', max_length=10)),
                ('date_issue', models.DateField(db_column='date_issue')),
                ('date_expiration', models.DateField(db_column='date_expiration')),
                ('passenger', models.ForeignKey(db_column='passenger', on_delete=django.db.models.deletion.DO_NOTHING, to='catraca_facil.passenger')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('value', models.BigIntegerField(db_column='value')),
                ('date_recharge', models.DateTimeField(auto_now=True, db_column='date_recharge')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartão', 'Cartão'), ('pix', 'Pix')], db_column='payment_method', default='Pix', max_length=10)),
                ('card', models.ForeignKey(db_column='card', on_delete=django.db.models.deletion.DO_NOTHING, to='catraca_facil.card')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UseCard',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('used_value', models.BigIntegerField(db_column='used_value')),
                ('date_used', models.DateTimeField(auto_now=True, db_column='date_used')),
                ('onboard_local', models.CharField(db_column='onboard_local', max_length=100)),
                ('bus', models.ForeignKey(db_column='bus', on_delete=django.db.models.deletion.DO_NOTHING, to='catraca_facil.bus')),
                ('card', models.ForeignKey(db_column='card', on_delete=django.db.models.deletion.DO_NOTHING, to='catraca_facil.card')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
