# Generated by Django 5.2.1 on 2025-05-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catraca_facil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(db_column='age', default=6),
        ),
    ]
